# Generated by Django 5.1.4 on 2026-05-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_tenant_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='logo',
        ),
        migrations.AddField(
            model_name='tenant',
            name='support_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
