# Generated by Django 5.1.4 on 2026-08-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='factura_electronica',
            field=models.BooleanField(default=False),
        ),
    ]
