# Generated by Django 5.1.4 on 2026-04-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0002_add_tenant_documents'),
        ('users', '0002_user_cedula_alter_user_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('cedula__isnull', False)), fields=('tenant', 'cedula'), name='unique_cedula_por_tenant'),
        ),
    ]
