# Generated by Django 5.1.4 on 2026-05-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_cedula_user_unique_cedula_por_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lead_cashier',
            field=models.BooleanField(default=False),
        ),
    ]
