# Generated by Django 5.1.4 on 2026-08-06 03:42

from django.db import migrations

# Literal instead of importing UserRole: a migration must not depend on the
# current state of the model module.
ROL_ADMIN = "ADMIN"


def clear_is_staff_on_tenant_admins(apps, schema_editor):
    """Retroactively drop `is_staff` from tenant admins.

    `_create_initial_admin` used to set `is_staff=True` on every tenant admin it
    created (and so did `seed_dev_data`); both were fixed, but only for admins
    created *after* the fix. `is_staff` is exactly what Django checks to let
    someone into `/admin/`, which bypasses DRF entirely — so every tenant admin
    created until now is still carrying that flag.

    SUPERADMIN rows are left untouched on purpose: they need `is_staff` to reach
    `/admin/`, which is their legitimate tool.
    """
    User = apps.get_model("users", "User")
    updated = User.objects.filter(rol=ROL_ADMIN, is_staff=True).update(is_staff=False)
    print(f"    → is_staff cleared on {updated} tenant admin(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_lead_cashier'),
    ]

    operations = [
        # No reverse: re-granting platform access to tenant admins is never the
        # thing you want to roll back to.
        migrations.RunPython(
            clear_is_staff_on_tenant_admins,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
