# Generated by Django 5.1.4 on 2026-04-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagen',
        ),
        migrations.AddField(
            model_name='category',
            name='imagen_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
