# Generated by Django 5.1.4 on 2026-08-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_precio_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
    ]
